export const TASKS = [
  {
    id: "t1",
    icon: "🧩",
    name: "Block Blast!",
    description: "Clear 20 puzzle levels in a row.",
    details: "A fast-paced block puzzle. Complete a 20-level streak to unlock the reward.",
    reward: 480,
    difficulty: "easy",
    etaMinutes: 6,
    eta: "~6 min",
    type: "trial",
    device: "all",
    geo: "global",
    genre: "Puzzle",
    badge: "hot",
    banner: "linear-gradient(135deg, #23d5ab 0%, #3aa0ff 55%, #ff8a5b 100%)",
    steps: [
      "Open the partner page and launch the game.",
      "Finish the quick tutorial.",
      "Complete 20 levels in a single session.",
      "Return here and confirm completion."
    ],
    requirements: ["New players only.", "One completion per device."]
  },
  {
    id: "t2",
    icon: "🪖",
    name: "Fortnite",
    description: "Finish the onboarding match and reach level 3.",
    details: "Complete the onboarding match and reach account level 3.",
    reward: 980,
    difficulty: "medium",
    etaMinutes: 15,
    eta: "~15 min",
    type: "register",
    device: "all",
    geo: "global",
    genre: "Action",
    badge: "recommend",
    banner: "linear-gradient(130deg, #1fa2ff 0%, #12d8fa 40%, #a6ffcb 100%)",
    steps: [
      "Open the offer and launch Fortnite.",
      "Sign in or create an account.",
      "Complete the onboarding match.",
      "Reach account level 3 and submit."
    ],
    requirements: ["New mobile installs only.", "Complete within 48 hours."]
  },
  {
    id: "t3",
    icon: "🧱",
    name: "Roblox",
    description: "Play 3 experiences and earn 50 coins.",
    details: "Explore three experiences and earn 50 in-game coins.",
    reward: 920,
    difficulty: "easy",
    etaMinutes: 12,
    eta: "~12 min",
    type: "download",
    device: "all",
    geo: "global",
    genre: "Platform",
    badge: "hot",
    banner: "linear-gradient(130deg, #0b8bff 0%, #13c48d 45%, #2a64ff 100%)",
    steps: [
      "Install and launch Roblox.",
      "Create or log into your account.",
      "Play 3 experiences.",
      "Earn 50 coins and confirm completion."
    ],
    requirements: ["First-time mobile installs only.", "One completion per account."]
  },
  {
    id: "t4",
    icon: "🌾",
    name: "Township",
    description: "Reach town level 4.",
    details: "Build your town and reach level 4 to qualify.",
    reward: 1350,
    difficulty: "medium",
    etaMinutes: 18,
    eta: "~18 min",
    type: "download",
    device: "all",
    geo: "global",
    genre: "Simulation",
    badge: "recommend",
    banner: "linear-gradient(130deg, #56ab2f 0%, #a8e063 45%, #c2ffd8 100%)",
    steps: [
      "Install and launch Township.",
      "Finish the introductory tutorial.",
      "Reach town level 4.",
      "Return and confirm completion."
    ],
    requirements: ["One completion per device.", "Keep the app installed during review."]
  },
  {
    id: "t5",
    icon: "🃏",
    name: "Pokémon TCG Pocket",
    description: "Open 5 packs and complete a duel tutorial.",
    details: "Open five packs and complete the duel tutorial to qualify.",
    reward: 1100,
    difficulty: "medium",
    etaMinutes: 15,
    eta: "~15 min",
    type: "register",
    device: "all",
    geo: "global",
    genre: "Card",
    badge: "new",
    banner: "linear-gradient(130deg, #f857a6 0%, #ff5858 40%, #ffc371 100%)",
    steps: [
      "Launch the game from the offer.",
      "Create or log into your account.",
      "Open 5 packs and complete the duel tutorial.",
      "Return and submit completion."
    ],
    requirements: ["New accounts only.", "Complete within 24 hours."]
  },
  {
    id: "t6",
    icon: "👑",
    name: "Royal Kingdom",
    description: "Reach level 10.",
    details: "Complete levels and reach level 10 to earn the reward.",
    reward: 1200,
    difficulty: "medium",
    etaMinutes: 16,
    eta: "~16 min",
    type: "trial",
    device: "all",
    geo: "global",
    genre: "Match-3",
    badge: "recommend",
    banner: "linear-gradient(130deg, #ff9966 0%, #ff5e62 45%, #ff3d77 100%)",
    steps: [
      "Open the game via the offer wall.",
      "Finish the tutorial levels.",
      "Reach level 10.",
      "Return and confirm completion."
    ],
    requirements: ["New installs only.", "No emulator usage."]
  },
  {
    id: "t7",
    icon: "🏰",
    name: "Clash Royale",
    description: "Win 3 battles in Arena 1.",
    details: "Complete three wins in Arena 1 to qualify.",
    reward: 950,
    difficulty: "medium",
    etaMinutes: 14,
    eta: "~14 min",
    type: "download",
    device: "all",
    geo: "global",
    genre: "Strategy",
    badge: "hot",
    banner: "linear-gradient(130deg, #00c6ff 0%, #0072ff 55%, #13c48d 100%)",
    steps: [
      "Install and launch Clash Royale.",
      "Complete the tutorial match.",
      "Win 3 battles in Arena 1.",
      "Return and submit completion."
    ],
    requirements: ["New players only.", "One completion per account."]
  },
  {
    id: "t8",
    icon: "🀄",
    name: "Vita Mahjong",
    description: "Clear 8 Mahjong boards.",
    details: "Complete eight boards to earn the reward.",
    reward: 980,
    difficulty: "medium",
    etaMinutes: 13,
    eta: "~13 min",
    type: "trial",
    device: "all",
    geo: "global",
    genre: "Board",
    badge: "new",
    banner: "linear-gradient(130deg, #f6d365 0%, #fda085 45%, #ff6fa2 100%)",
    steps: [
      "Launch Vita Mahjong.",
      "Complete the tutorial board.",
      "Clear 8 boards total.",
      "Return to confirm completion."
    ],
    requirements: ["One completion per account.", "No emulator usage."]
  },
  {
    id: "t9",
    icon: "❄️",
    name: "Whiteout Survival",
    description: "Upgrade the furnace to level 5.",
    details: "Reach furnace level 5 to unlock the reward.",
    reward: 1500,
    difficulty: "hard",
    etaMinutes: 25,
    eta: "~25 min",
    type: "download",
    device: "all",
    geo: "global",
    genre: "Strategy",
    badge: "recommend",
    banner: "linear-gradient(130deg, #1fa2ff 0%, #12d8fa 40%, #a6ffcb 100%)",
    steps: [
      "Install and launch the game.",
      "Complete the settlement tutorial.",
      "Upgrade the furnace to level 5.",
      "Return and submit completion."
    ],
    requirements: ["New players only.", "Keep the app installed during review."]
  },
  {
    id: "t10",
    icon: "🛡️",
    name: "Last War: Survival",
    description: "Reach commander level 8.",
    details: "Advance to commander level 8 to qualify.",
    reward: 1700,
    difficulty: "hard",
    etaMinutes: 28,
    eta: "~28 min",
    type: "purchase",
    device: "all",
    geo: "global",
    genre: "Strategy",
    badge: "hot",
    banner: "linear-gradient(130deg, #f00000 0%, #dc281e 35%, #f7971e 100%)",
    steps: [
      "Install and launch the game.",
      "Complete the starter missions.",
      "Reach commander level 8.",
      "Return and submit completion."
    ],
    requirements: ["In-app purchases are optional.", "Complete within 72 hours."]
  },
  {
    id: "t11",
    icon: "🧱",
    name: "Color Block Jam",
    description: "Clear 15 color levels.",
    details: "Complete 15 levels to unlock the reward.",
    reward: 560,
    difficulty: "easy",
    etaMinutes: 7,
    eta: "~7 min",
    type: "trial",
    device: "all",
    geo: "global",
    genre: "Puzzle",
    badge: "new",
    banner: "linear-gradient(130deg, #f953c6 0%, #b91d73 40%, #6a82fb 100%)",
    steps: [
      "Launch the game via the offer.",
      "Finish the quick tutorial.",
      "Clear 15 levels.",
      "Return and submit completion."
    ],
    requirements: ["No task repeats on the same account.", "Complete in one session."]
  },
  {
    id: "t12",
    icon: "🏃",
    name: "Subway Surfers",
    description: "Run a total of 3,000 meters.",
    details: "Accumulate 3,000 meters across runs.",
    reward: 740,
    difficulty: "easy",
    etaMinutes: 8,
    eta: "~8 min",
    type: "register",
    device: "all",
    geo: "global",
    genre: "Runner",
    badge: "hot",
    banner: "linear-gradient(130deg, #2af598 0%, #009efd 40%, #6a11cb 100%)",
    steps: [
      "Start the game from the offer.",
      "Complete the first run tutorial.",
      "Reach 3,000 meters total distance.",
      "Return and submit completion."
    ],
    requirements: ["New installs only.", "Complete within 24 hours."]
  },
  {
    id: "t13",
    icon: "🧹",
    name: "Perfect Tidy",
    description: "Complete 3 tidy challenges.",
    details: "Organize rooms, sort items, and finish 3 tidy stages.",
    reward: 520,
    difficulty: "easy",
    etaMinutes: 7,
    eta: "~7 min",
    type: "trial",
    device: "all",
    geo: "global",
    genre: "Casual",
    badge: "new",
    banner: "linear-gradient(140deg, #00f5a0 0%, #00d9f5 45%, #4facfe 100%)",
    steps: [
      "Open the offer and start the game.",
      "Complete the first tidy tutorial.",
      "Finish 3 tidy challenges.",
      "Return and submit the task."
    ],
    requirements: ["Complete in one session.", "No emulator usage."]
  },
  {
    id: "t14",
    icon: "👑",
    name: "Royal Match",
    description: "Reach level 15.",
    details: "Advance to level 15 to unlock the reward.",
    reward: 1600,
    difficulty: "medium",
    etaMinutes: 20,
    eta: "~20 min",
    type: "survey",
    device: "all",
    geo: "global",
    genre: "Match-3",
    badge: "hot",
    banner: "linear-gradient(130deg, #f857a6 0%, #ff5858 40%, #ffc371 100%)",
    steps: [
      "Install and launch the game.",
      "Finish the intro levels.",
      "Reach level 15.",
      "Complete the short in-game feedback survey.",
      "Return and submit completion."
    ],
    requirements: ["New players only.", "Survey is required for validation."]
  },
  {
    id: "t15",
    icon: "🎲",
    name: "MONOPOLY GO!",
    description: "Complete the first board and collect rewards.",
    details: "Finish your first board to qualify for the reward.",
    reward: 1400,
    difficulty: "medium",
    etaMinutes: 18,
    eta: "~18 min",
    type: "register",
    device: "all",
    geo: "global",
    genre: "Board",
    badge: "recommend",
    banner: "linear-gradient(130deg, #1fa2ff 0%, #12d8fa 40%, #a6ffcb 100%)",
    steps: [
      "Open the game from the offer wall.",
      "Finish the intro rolls.",
      "Complete the first board.",
      "Return and confirm completion."
    ],
    requirements: ["First-time installs only.", "No VPN usage."]
  },
  {
    id: "t16",
    icon: "🏹",
    name: "Kingshot",
    description: "Unlock chapter 3 and build a level 5 barracks.",
    details: "Reach chapter 3 and upgrade a barracks to level 5.",
    reward: 1500,
    difficulty: "medium",
    etaMinutes: 22,
    eta: "~22 min",
    type: "download",
    device: "all",
    geo: "global",
    genre: "Strategy",
    badge: "new",
    banner: "linear-gradient(130deg, #0b8bff 0%, #13c48d 45%, #2a64ff 100%)",
    steps: [
      "Install and launch Kingshot.",
      "Complete the main tutorial.",
      "Reach chapter 3 and upgrade barracks to level 5.",
      "Return and confirm completion."
    ],
    requirements: ["New players only.", "Complete within 72 hours."]
  },
  {
    id: "t17",
    icon: "🚌",
    name: "Bus Escape: Traffic Jam",
    description: "Solve 10 traffic jam stages.",
    details: "Clear 10 stages of traffic puzzles.",
    reward: 820,
    difficulty: "medium",
    etaMinutes: 12,
    eta: "~12 min",
    type: "trial",
    device: "all",
    geo: "us",
    genre: "Puzzle",
    badge: "recommend",
    banner: "linear-gradient(130deg, #00c6ff 0%, #0072ff 55%, #13c48d 100%)",
    steps: [
      "Open the game from the offer wall.",
      "Complete the tutorial stage.",
      "Solve 10 traffic jam stages.",
      "Return and submit the task."
    ],
    requirements: ["US traffic only.", "Do not clear app data before submission."]
  },
  {
    id: "t18",
    icon: "🎯",
    name: "Call of Duty: Mobile",
    description: "Reach player level 5 and complete 2 multiplayer matches.",
    details: "Finish two multiplayer matches and reach level 5.",
    reward: 1750,
    difficulty: "hard",
    etaMinutes: 25,
    eta: "~25 min",
    type: "download",
    device: "all",
    geo: "global",
    genre: "Shooter",
    badge: "hot",
    banner: "linear-gradient(130deg, #f12711 0%, #f5af19 35%, #3ca55c 100%)",
    steps: [
      "Install and launch the game.",
      "Complete the tutorial match.",
      "Play 2 multiplayer matches.",
      "Reach player level 5 and submit."
    ],
    requirements: ["New players only.", "Stable connection required."]
  },
  {
    id: "t19",
    icon: "🎹",
    name: "Magic Tiles 3: Piano Game",
    description: "Finish 3 songs in classic mode.",
    details: "Tap along and complete three full songs in classic mode.",
    reward: 980,
    difficulty: "medium",
    etaMinutes: 12,
    eta: "~12 min",
    type: "trial",
    device: "all",
    geo: "global",
    genre: "Music",
    badge: "recommend",
    banner: "linear-gradient(130deg, #667eea 0%, #764ba2 30%, #ff9a9e 100%)",
    steps: [
      "Open the game and choose classic mode.",
      "Finish the tutorial song.",
      "Complete 3 songs total.",
      "Return here to confirm completion."
    ],
    requirements: ["One completion per account.", "No external input tools."]
  },
  {
    id: "t20",
    icon: "📦",
    name: "Goods Puzzle: Sort Challenge",
    description: "Sort 60 items into correct bins.",
    details: "Sort items by category and finish 60 correct placements.",
    reward: 720,
    difficulty: "medium",
    etaMinutes: 10,
    eta: "~10 min",
    type: "survey",
    device: "all",
    geo: "global",
    genre: "Sorting",
    badge: "new",
    banner: "linear-gradient(130deg, #56ab2f 0%, #a8e063 45%, #c2ffd8 100%)",
    steps: [
      "Start the sorting tutorial.",
      "Finish two rounds of sorting.",
      "Reach 60 correct placements.",
      "Complete the short in-game feedback survey.",
      "Return and submit the task."
    ],
    requirements: ["Survey is required for validation.", "One completion per account."]
  }
];

export const LEADERBOARD_SEED = [
  { id: "l1", avatar: "🦊", nickname: "NeoFox", weeklyPoints: 9820 },
  { id: "l2", avatar: "🐼", nickname: "PandaRay", weeklyPoints: 9300 },
  { id: "l3", avatar: "🦁", nickname: "LeoStrike", weeklyPoints: 9100 },
  { id: "l4", avatar: "🐻", nickname: "BearByte", weeklyPoints: 8680 },
  { id: "l5", avatar: "🐯", nickname: "TigerLoop", weeklyPoints: 8450 },
  { id: "l6", avatar: "🦉", nickname: "NightOwl", weeklyPoints: 8200 },
  { id: "l7", avatar: "🐙", nickname: "OctaPlay", weeklyPoints: 7980 },
  { id: "l8", avatar: "🦄", nickname: "UnicornGG", weeklyPoints: 7760 },
  { id: "l9", avatar: "🐧", nickname: "PenguWin", weeklyPoints: 7520 },
  { id: "l10", avatar: "🐨", nickname: "KoalaTap", weeklyPoints: 7350 },
  { id: "l11", avatar: "🐸", nickname: "FrogRush", weeklyPoints: 7160 },
  { id: "l12", avatar: "🦋", nickname: "BlueWing", weeklyPoints: 7020 },
  { id: "l13", avatar: "🦀", nickname: "CrabCore", weeklyPoints: 6890 },
  { id: "l14", avatar: "🐳", nickname: "WhalePing", weeklyPoints: 6700 },
  { id: "l15", avatar: "🕹️", nickname: "RetroBit", weeklyPoints: 6510 },
  { id: "l16", avatar: "🧩", nickname: "PuzzleZed", weeklyPoints: 6320 },
  { id: "l17", avatar: "🎯", nickname: "AimAce", weeklyPoints: 6180 },
  { id: "l18", avatar: "🎲", nickname: "DiceFlow", weeklyPoints: 6010 },
  { id: "l19", avatar: "🛡️", nickname: "ShieldPro", weeklyPoints: 5860 },
  { id: "l20", avatar: "⚡", nickname: "VoltRun", weeklyPoints: 5700 }
];

export const FAQ_ITEMS = [
  {
    id: "faq1",
    question: "Why are rewards not credited instantly after submission?",
    answer: "Tasks enter a review queue to validate partner rules. In this demo, pending tasks auto-approve in about 5 seconds."
  },
  {
    id: "faq2",
    question: "Can I complete the same task multiple times?",
    answer: "Most tasks can be completed once per account. See each offer's requirements for details."
  },
  {
    id: "faq3",
    question: "How long does redemption take?",
    answer: "This demo instantly creates redemption records. Real platforms usually need additional processing time."
  },
  {
    id: "faq4",
    question: "Why was my task rejected?",
    answer: "Common reasons include duplicate devices, unmet requirements, or suspicious tools. Check task steps and requirements first."
  }
];

export const REDEEM_OPTIONS = [
  {
    id: "paypal",
    icon: "💸",
    label: "PayPal Cashout",
    minimumPoints: 500,
    ratio: 100
  },
  {
    id: "giftcard",
    icon: "🎁",
    label: "Gift Card (Amazon/Steam/iTunes)",
    minimumPoints: 800,
    ratio: 100
  },
  {
    id: "gamecoin",
    icon: "🪙",
    label: "In-Game Currency",
    minimumPoints: 300,
    ratio: 100
  }
];
